apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc-deployment
  labels:
    app: kfc-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kfc-static
  template:
    metadata:
      labels:
        app: kfc-static
    spec:
      containers:
      - name: kfc-static
        image: hanif040/kfc-static:latest
        ports:
        - containerPort: 80
