apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc-deployment
  labels:
    app: kfc-capstone-dockerhub-repo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kfc-capstone-dockerhub-repo
  template:
    metadata:
      labels:
        app: kfc-capstone-dockerhub-repo
    spec:
      containers:
      - name: kfc-capstone
        image: nazeefkhan228/kfc-capstone-dockerhub-repo:2
        ports:
        - containerPort: 80
